Models/Atividade.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hello.Models;

public class Atividade
{
    public string Descricao { get; set; }
    public float Dificuldade { get; set; }
    public string Tipo { get; set; }
    public int Participantes { get; set; }
    public string Link { get; set; }

    public Atividade(Resposta resposta, string tipo)
    {
        this.Descricao = resposta.Activity;
        this.Dificuldade = resposta.Accessibility;
        this.Tipo = tipo;
        this.Participantes = resposta.Participants;
        this.Link = resposta.Link ?? "";
    }
}

Models/ErrorViewModel.cs
namespace Hello.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Resposta.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hello.Models;

public class Resposta
{
    public string Activity { get; set; }
    public string Type { get; set; }
    public int Participants { get; set; }
    public float Price { get; set; }
    public string Link { get; set; }
    public string Key { get; set; }
    public float Accessibility { get; set; }
    public Resposta(
        string activity,
        string type,
        int participants,
        float price,
        string link,
        string key,
        float accessibility
    ) {
        this.Activity = activity;
        this.Type = type;
        this.Participants = participants;
        this.Price = price;
        this.Link = link;
        this.Key = key;
        this.Accessibility = accessibility;
    }
}

Models/Serie.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hello.Models;

public class Serie
{
    [Required]
    [StringLength(60, MinimumLength = 3)]
    public string Nome { get; set; }

    [Required]
    [Range(-1, 1)]
    public int Interesse { get; set; }

    public Serie(string nome, int interesse)
    {
        this.Nome = nome;
        this.Interesse = interesse;
    }
}

Controllers/ApiController.cs
using System;
using System.Globalization;
using System.Diagnostics;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Hello.Models;
using RestSharp;

namespace Hello.Controllers;

public class ApiController : Controller
{
    private readonly ILogger<ApiController> _logger;

    private static string[] tiposEn = new string[] {
        "education", "recreational", "social",
        "diy", "charity", "cooking", 
        "relaxation", "music", "busywork"
    };

    private static string[] tiposPt = new string[] {
        "Educativa", "Divertida", "Social",
        "Gambiarra", "Caridade", "Cozinha", 
        "Relaxante", "Música", "Mata Tempo"
    };

    public ApiController(ILogger<ApiController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<ActionResult> Procura(double dificuldade, int tipo, int participantes)
    {
        if (dificuldade != 1)
        {
            // Vem errado quando é decimal
            dificuldade /= 100.0;
        }
        var difFormat = dificuldade.ToString("n2", CultureInfo.InvariantCulture);
        var difFormat = dificuldade.ToString("n2", CultureInfo.InvariantCulture);

        var tipoEn = tiposEn[tipo];
        var tipoPt = tiposPt[tipo];

        var options = new RestClientOptions("https://www.boredapi.com/api/");
        var client = new RestClient(options);

        Resposta resposta = await client.GetJsonAsync<Resposta>(
            $"activity?type={tipoEn}&participants={participantes}&maxaccessibility={difFormat}"
            $"activity?type={tipoEn}&participants={participantes}&maxaccessibility={difFormat}"
        );

        return View(new Atividade(resposta, tipoPt));
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Controllers/EscolhaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Hello.Models;
using System.Text.Encodings.Web;

namespace Hello.Controllers;

public class EscolhaController : Controller
{
    private readonly ILogger<EscolhaController> _logger;

    private static Serie PegaAleatoria(Serie[] series) {
        const int pesoBase = 2;
        var indices = new List<int>();

        int i = 0;
        foreach (var serie in series)
        {
            for (int j = 0; j < pesoBase + serie.Interesse; j++)
            {
                indices.Add(i);
            }
            i++;
        }

        var rand = new Random();
        var escolha = rand.Next(0, indices.Count);
        var indice = indices[escolha];
        return series[indice];
        
    }

    public EscolhaController(ILogger<EscolhaController> logger)
    {
        _logger = logger;
    }

    //
    // GET: /Escolha/
    public string Index()
    {
        return "Padrão...";
    }

    // GET: /Escolha/Mostra/
    public IActionResult Mostra()
    {
        // Buscaria isso do DB
        var series = new Serie[]
        {
            new Serie("Wakfu", 0),
            new Serie("The Wire", 1),
            new Serie("Seinfeld", -1),
            new Serie("Barry", 1),
            new Serie("The Expanse", 1),
        };

        return View(PegaAleatoria(series));
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Hello.Models;

namespace Hello.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        List<Serie> _series = new();
        return View(_series);
    }

    public IActionResult Add(string nome, int interesse)
    {
        _logger.LogInformation($"Adicionada série {nome} com interesse {interesse}");
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Exemplo()
    {
        var _series = new Serie[]
        {
            new Serie("Wakfu", 0),
            new Serie("The Wire", 1),
            new Serie("Seinfeld", -1),
            new Serie("Barry", 1),
            new Serie("The Expanse", 1),
        };
        return View("Index", _series);
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Views/Escolha/Mostra.cshtml
@model Hello.Models.Serie

@{
    ViewData["Title"] = "Série Escolhida";
}

<div class="text-center">
    <h1 class="display-4">
        @Html.DisplayFor(model => model.Nome)
    </h1>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Hello.Models.Serie>

@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Ó céus, o que assistir?</h1>

    <div class="container">
        @foreach (var serie in Model)
        {
            <div class="row justify-content-center py-2">
                <div class="col-md-4 py-1 bg-light rounded-start border border-2">@serie.Nome</div>
                <div class="col-md-2 py-1 bg-light rounded-end border border-2">
                    @switch (serie.Interesse)
                        {
                            case -1: <span>🙁</span>
                            break;
                            case 0: <span>🙂</span>
                            break;
                            case 1: <span>😃</span>
                            break;
                        }
                </div>
            </div>
        }
    </div>

    <form asp-action="Add" class="row justify-content-center g-3">
        <div class="col-md-4">
            <label for="nome" class="form-label">Nome</label>
            <input data-val="true" type="text" class="form-control" id="nome" name="nome">
        </div>
        
        <div class="col-md-2">
            <label for="interesse" class="form-label">Interesse</label>
            <input type="range" class="form-control" id="interesse" name="interesse" min=-1 max=1>
        </div>

        <div class="col-12">
            <button type="submit" id="btn-add" class="btn btn-secondary col-1">Adicionar</button>
            <button asp-controller="Escolha" asp-action="Mostra" class="btn btn-success col-1">Escolher</button>
        </div>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teste .NET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hello.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Exemplo">Exemplo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Api" asp-action="Index">API</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Teste .NET
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>